export { default as AboutContainer } from './About/AboutContainer'
export { default as ProdListContainer } from './ProductList/ProdListContainer'
export { default as ProductViewerContainer } from './ProductViewer/ProductViewerContainer'
export { default as PayComponentContainer } from './PayComponent/PayComponentContainer'
export { default as SliderContainer } from './Slider/SliderContainer' 